
package tomcatservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ClassRoom", targetNamespace = "http://tomcatservice/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ClassRoom {


    /**
     * 
     * @return
     *     returns java.util.List<tomcatservice.FontysStudent>
     */
    @WebMethod(operationName = "GetStudentsInClass")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetStudentsInClass", targetNamespace = "http://tomcatservice/", className = "tomcatservice.GetStudentsInClass")
    @ResponseWrapper(localName = "GetStudentsInClassResponse", targetNamespace = "http://tomcatservice/", className = "tomcatservice.GetStudentsInClassResponse")
    @Action(input = "http://tomcatservice/ClassRoom/GetStudentsInClassRequest", output = "http://tomcatservice/ClassRoom/GetStudentsInClassResponse")
    public List<FontysStudent> getStudentsInClass();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "StartClass")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "StartClass", targetNamespace = "http://tomcatservice/", className = "tomcatservice.StartClass")
    @ResponseWrapper(localName = "StartClassResponse", targetNamespace = "http://tomcatservice/", className = "tomcatservice.StartClassResponse")
    @Action(input = "http://tomcatservice/ClassRoom/StartClassRequest", output = "http://tomcatservice/ClassRoom/StartClassResponse")
    public String startClass();

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "RemoveStudent")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "RemoveStudent", targetNamespace = "http://tomcatservice/", className = "tomcatservice.RemoveStudent")
    @ResponseWrapper(localName = "RemoveStudentResponse", targetNamespace = "http://tomcatservice/", className = "tomcatservice.RemoveStudentResponse")
    @Action(input = "http://tomcatservice/ClassRoom/RemoveStudentRequest", output = "http://tomcatservice/ClassRoom/RemoveStudentResponse")
    public boolean removeStudent(
        @WebParam(name = "arg0", targetNamespace = "")
        FontysStudent arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "AddStudent")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "AddStudent", targetNamespace = "http://tomcatservice/", className = "tomcatservice.AddStudent")
    @ResponseWrapper(localName = "AddStudentResponse", targetNamespace = "http://tomcatservice/", className = "tomcatservice.AddStudentResponse")
    @Action(input = "http://tomcatservice/ClassRoom/AddStudentRequest", output = "http://tomcatservice/ClassRoom/AddStudentResponse")
    public boolean addStudent(
        @WebParam(name = "arg0", targetNamespace = "")
        FontysStudent arg0);

}
