
package tomcatservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CompService", targetNamespace = "http://tomcatservice/", wsdlLocation = "http://localhost:8080/TomcatService/comp?wsdl")
public class CompService
    extends Service
{

    private final static URL COMPSERVICE_WSDL_LOCATION;
    private final static WebServiceException COMPSERVICE_EXCEPTION;
    private final static QName COMPSERVICE_QNAME = new QName("http://tomcatservice/", "CompService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/TomcatService/comp?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COMPSERVICE_WSDL_LOCATION = url;
        COMPSERVICE_EXCEPTION = e;
    }

    public CompService() {
        super(__getWsdlLocation(), COMPSERVICE_QNAME);
    }

    public CompService(WebServiceFeature... features) {
        super(__getWsdlLocation(), COMPSERVICE_QNAME, features);
    }

    public CompService(URL wsdlLocation) {
        super(wsdlLocation, COMPSERVICE_QNAME);
    }

    public CompService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COMPSERVICE_QNAME, features);
    }

    public CompService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CompService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Comp
     */
    @WebEndpoint(name = "CompPort")
    public Comp getCompPort() {
        return super.getPort(new QName("http://tomcatservice/", "CompPort"), Comp.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Comp
     */
    @WebEndpoint(name = "CompPort")
    public Comp getCompPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://tomcatservice/", "CompPort"), Comp.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COMPSERVICE_EXCEPTION!= null) {
            throw COMPSERVICE_EXCEPTION;
        }
        return COMPSERVICE_WSDL_LOCATION;
    }

}
