
package tomcatservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Comp", targetNamespace = "http://tomcatservice/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Comp {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "RemoveStudent")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "RemoveStudent", targetNamespace = "http://tomcatservice/", className = "tomcatservice.RemoveStudent")
    @ResponseWrapper(localName = "RemoveStudentResponse", targetNamespace = "http://tomcatservice/", className = "tomcatservice.RemoveStudentResponse")
    @Action(input = "http://tomcatservice/Comp/RemoveStudentRequest", output = "http://tomcatservice/Comp/RemoveStudentResponse")
    public boolean removeStudent(
        @WebParam(name = "arg0", targetNamespace = "")
        Student arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Fail")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Fail", targetNamespace = "http://tomcatservice/", className = "tomcatservice.Fail")
    @ResponseWrapper(localName = "FailResponse", targetNamespace = "http://tomcatservice/", className = "tomcatservice.FailResponse")
    @Action(input = "http://tomcatservice/Comp/FailRequest", output = "http://tomcatservice/Comp/FailResponse")
    public String fail();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Pass")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Pass", targetNamespace = "http://tomcatservice/", className = "tomcatservice.Pass")
    @ResponseWrapper(localName = "PassResponse", targetNamespace = "http://tomcatservice/", className = "tomcatservice.PassResponse")
    @Action(input = "http://tomcatservice/Comp/PassRequest", output = "http://tomcatservice/Comp/PassResponse")
    public String pass();

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "AddStudent")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "AddStudent", targetNamespace = "http://tomcatservice/", className = "tomcatservice.AddStudent")
    @ResponseWrapper(localName = "AddStudentResponse", targetNamespace = "http://tomcatservice/", className = "tomcatservice.AddStudentResponse")
    @Action(input = "http://tomcatservice/Comp/AddStudentRequest", output = "http://tomcatservice/Comp/AddStudentResponse")
    public boolean addStudent(
        @WebParam(name = "arg0", targetNamespace = "")
        Student arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStundentName", targetNamespace = "http://tomcatservice/", className = "tomcatservice.GetStundentName")
    @ResponseWrapper(localName = "getStundentNameResponse", targetNamespace = "http://tomcatservice/", className = "tomcatservice.GetStundentNameResponse")
    @Action(input = "http://tomcatservice/Comp/getStundentNameRequest", output = "http://tomcatservice/Comp/getStundentNameResponse")
    public String getStundentName();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "StartClass")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "StartClass", targetNamespace = "http://tomcatservice/", className = "tomcatservice.StartClass")
    @ResponseWrapper(localName = "StartClassResponse", targetNamespace = "http://tomcatservice/", className = "tomcatservice.StartClassResponse")
    @Action(input = "http://tomcatservice/Comp/StartClassRequest", output = "http://tomcatservice/Comp/StartClassResponse")
    public String startClass();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setStundentName", targetNamespace = "http://tomcatservice/", className = "tomcatservice.SetStundentName")
    @ResponseWrapper(localName = "setStundentNameResponse", targetNamespace = "http://tomcatservice/", className = "tomcatservice.SetStundentNameResponse")
    @Action(input = "http://tomcatservice/Comp/setStundentNameRequest", output = "http://tomcatservice/Comp/setStundentNameResponse")
    public void setStundentName(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
