
package tomcatservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FontysStudentService", targetNamespace = "http://tomcatservice/", wsdlLocation = "http://localhost:8080/TomcatService/student?wsdl")
public class FontysStudentService
    extends Service
{

    private final static URL FONTYSSTUDENTSERVICE_WSDL_LOCATION;
    private final static WebServiceException FONTYSSTUDENTSERVICE_EXCEPTION;
    private final static QName FONTYSSTUDENTSERVICE_QNAME = new QName("http://tomcatservice/", "FontysStudentService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/TomcatService/student?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FONTYSSTUDENTSERVICE_WSDL_LOCATION = url;
        FONTYSSTUDENTSERVICE_EXCEPTION = e;
    }

    public FontysStudentService() {
        super(__getWsdlLocation(), FONTYSSTUDENTSERVICE_QNAME);
    }

    public FontysStudentService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FONTYSSTUDENTSERVICE_QNAME, features);
    }

    public FontysStudentService(URL wsdlLocation) {
        super(wsdlLocation, FONTYSSTUDENTSERVICE_QNAME);
    }

    public FontysStudentService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FONTYSSTUDENTSERVICE_QNAME, features);
    }

    public FontysStudentService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FontysStudentService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Student
     */
    @WebEndpoint(name = "FontysStudentPort")
    public Student getFontysStudentPort() {
        return super.getPort(new QName("http://tomcatservice/", "FontysStudentPort"), Student.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Student
     */
    @WebEndpoint(name = "FontysStudentPort")
    public Student getFontysStudentPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://tomcatservice/", "FontysStudentPort"), Student.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FONTYSSTUDENTSERVICE_EXCEPTION!= null) {
            throw FONTYSSTUDENTSERVICE_EXCEPTION;
        }
        return FONTYSSTUDENTSERVICE_WSDL_LOCATION;
    }

}
