
package tomcatservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ICompositeServ", targetNamespace = "http://tomcatservice/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ICompositeServ {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getClassName", targetNamespace = "http://tomcatservice/", className = "tomcatservice.GetClassName")
    @ResponseWrapper(localName = "getClassNameResponse", targetNamespace = "http://tomcatservice/", className = "tomcatservice.GetClassNameResponse")
    @Action(input = "http://tomcatservice/ICompositeServ/getClassNameRequest", output = "http://tomcatservice/ICompositeServ/getClassNameResponse")
    public String getClassName();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setClassName", targetNamespace = "http://tomcatservice/", className = "tomcatservice.SetClassName")
    @ResponseWrapper(localName = "setClassNameResponse", targetNamespace = "http://tomcatservice/", className = "tomcatservice.SetClassNameResponse")
    @Action(input = "http://tomcatservice/ICompositeServ/setClassNameRequest", output = "http://tomcatservice/ICompositeServ/setClassNameResponse")
    public void setClassName(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStundentName", targetNamespace = "http://tomcatservice/", className = "tomcatservice.GetStundentName")
    @ResponseWrapper(localName = "getStundentNameResponse", targetNamespace = "http://tomcatservice/", className = "tomcatservice.GetStundentNameResponse")
    @Action(input = "http://tomcatservice/ICompositeServ/getStundentNameRequest", output = "http://tomcatservice/ICompositeServ/getStundentNameResponse")
    public String getStundentName();

    /**
     * 
     * @return
     *     returns tomcatservice.SmallClassRoom
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getClassRoom", targetNamespace = "http://tomcatservice/", className = "tomcatservice.GetClassRoom")
    @ResponseWrapper(localName = "getClassRoomResponse", targetNamespace = "http://tomcatservice/", className = "tomcatservice.GetClassRoomResponse")
    @Action(input = "http://tomcatservice/ICompositeServ/getClassRoomRequest", output = "http://tomcatservice/ICompositeServ/getClassRoomResponse")
    public SmallClassRoom getClassRoom();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setStundentName", targetNamespace = "http://tomcatservice/", className = "tomcatservice.SetStundentName")
    @ResponseWrapper(localName = "setStundentNameResponse", targetNamespace = "http://tomcatservice/", className = "tomcatservice.SetStundentNameResponse")
    @Action(input = "http://tomcatservice/ICompositeServ/setStundentNameRequest", output = "http://tomcatservice/ICompositeServ/setStundentNameResponse")
    public void setStundentName(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMaxStudents", targetNamespace = "http://tomcatservice/", className = "tomcatservice.GetMaxStudents")
    @ResponseWrapper(localName = "getMaxStudentsResponse", targetNamespace = "http://tomcatservice/", className = "tomcatservice.GetMaxStudentsResponse")
    @Action(input = "http://tomcatservice/ICompositeServ/getMaxStudentsRequest", output = "http://tomcatservice/ICompositeServ/getMaxStudentsResponse")
    public int getMaxStudents();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Fail")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Fail", targetNamespace = "http://tomcatservice/", className = "tomcatservice.Fail")
    @ResponseWrapper(localName = "FailResponse", targetNamespace = "http://tomcatservice/", className = "tomcatservice.FailResponse")
    @Action(input = "http://tomcatservice/ICompositeServ/FailRequest", output = "http://tomcatservice/ICompositeServ/FailResponse")
    public String fail();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setStudents", targetNamespace = "http://tomcatservice/", className = "tomcatservice.SetStudents")
    @ResponseWrapper(localName = "setStudentsResponse", targetNamespace = "http://tomcatservice/", className = "tomcatservice.SetStudentsResponse")
    @Action(input = "http://tomcatservice/ICompositeServ/setStudentsRequest", output = "http://tomcatservice/ICompositeServ/setStudentsResponse")
    public void setStudents(
        @WebParam(name = "arg0", targetNamespace = "")
        List<Student> arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setStudent", targetNamespace = "http://tomcatservice/", className = "tomcatservice.SetStudent")
    @ResponseWrapper(localName = "setStudentResponse", targetNamespace = "http://tomcatservice/", className = "tomcatservice.SetStudentResponse")
    @Action(input = "http://tomcatservice/ICompositeServ/setStudentRequest", output = "http://tomcatservice/ICompositeServ/setStudentResponse")
    public void setStudent(
        @WebParam(name = "arg0", targetNamespace = "")
        Student arg0);

    /**
     * 
     * @return
     *     returns tomcatservice.Student
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStudent", targetNamespace = "http://tomcatservice/", className = "tomcatservice.GetStudent")
    @ResponseWrapper(localName = "getStudentResponse", targetNamespace = "http://tomcatservice/", className = "tomcatservice.GetStudentResponse")
    @Action(input = "http://tomcatservice/ICompositeServ/getStudentRequest", output = "http://tomcatservice/ICompositeServ/getStudentResponse")
    public Student getStudent();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Pass")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Pass", targetNamespace = "http://tomcatservice/", className = "tomcatservice.Pass")
    @ResponseWrapper(localName = "PassResponse", targetNamespace = "http://tomcatservice/", className = "tomcatservice.PassResponse")
    @Action(input = "http://tomcatservice/ICompositeServ/PassRequest", output = "http://tomcatservice/ICompositeServ/PassResponse")
    public String pass();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setMaxStudents", targetNamespace = "http://tomcatservice/", className = "tomcatservice.SetMaxStudents")
    @ResponseWrapper(localName = "setMaxStudentsResponse", targetNamespace = "http://tomcatservice/", className = "tomcatservice.SetMaxStudentsResponse")
    @Action(input = "http://tomcatservice/ICompositeServ/setMaxStudentsRequest", output = "http://tomcatservice/ICompositeServ/setMaxStudentsResponse")
    public void setMaxStudents(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns java.util.List<tomcatservice.Student>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStudents", targetNamespace = "http://tomcatservice/", className = "tomcatservice.GetStudents")
    @ResponseWrapper(localName = "getStudentsResponse", targetNamespace = "http://tomcatservice/", className = "tomcatservice.GetStudentsResponse")
    @Action(input = "http://tomcatservice/ICompositeServ/getStudentsRequest", output = "http://tomcatservice/ICompositeServ/getStudentsResponse")
    public List<Student> getStudents();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setClassRoom", targetNamespace = "http://tomcatservice/", className = "tomcatservice.SetClassRoom")
    @ResponseWrapper(localName = "setClassRoomResponse", targetNamespace = "http://tomcatservice/", className = "tomcatservice.SetClassRoomResponse")
    @Action(input = "http://tomcatservice/ICompositeServ/setClassRoomRequest", output = "http://tomcatservice/ICompositeServ/setClassRoomResponse")
    public void setClassRoom(
        @WebParam(name = "arg0", targetNamespace = "")
        SmallClassRoom arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "AddStudent")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "AddStudent", targetNamespace = "http://tomcatservice/", className = "tomcatservice.AddStudent")
    @ResponseWrapper(localName = "AddStudentResponse", targetNamespace = "http://tomcatservice/", className = "tomcatservice.AddStudentResponse")
    @Action(input = "http://tomcatservice/ICompositeServ/AddStudentRequest", output = "http://tomcatservice/ICompositeServ/AddStudentResponse")
    public boolean addStudent(
        @WebParam(name = "arg0", targetNamespace = "")
        Student arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "RemoveStudent")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "RemoveStudent", targetNamespace = "http://tomcatservice/", className = "tomcatservice.RemoveStudent")
    @ResponseWrapper(localName = "RemoveStudentResponse", targetNamespace = "http://tomcatservice/", className = "tomcatservice.RemoveStudentResponse")
    @Action(input = "http://tomcatservice/ICompositeServ/RemoveStudentRequest", output = "http://tomcatservice/ICompositeServ/RemoveStudentResponse")
    public boolean removeStudent(
        @WebParam(name = "arg0", targetNamespace = "")
        Student arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "StartClass")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "StartClass", targetNamespace = "http://tomcatservice/", className = "tomcatservice.StartClass")
    @ResponseWrapper(localName = "StartClassResponse", targetNamespace = "http://tomcatservice/", className = "tomcatservice.StartClassResponse")
    @Action(input = "http://tomcatservice/ICompositeServ/StartClassRequest", output = "http://tomcatservice/ICompositeServ/StartClassResponse")
    public String startClass();

}
