
package tomcatservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SmallClassRoomService", targetNamespace = "http://tomcatservice/", wsdlLocation = "http://localhost:8080/TomcatService/class?wsdl")
public class SmallClassRoomService
    extends Service
{

    private final static URL SMALLCLASSROOMSERVICE_WSDL_LOCATION;
    private final static WebServiceException SMALLCLASSROOMSERVICE_EXCEPTION;
    private final static QName SMALLCLASSROOMSERVICE_QNAME = new QName("http://tomcatservice/", "SmallClassRoomService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/TomcatService/class?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SMALLCLASSROOMSERVICE_WSDL_LOCATION = url;
        SMALLCLASSROOMSERVICE_EXCEPTION = e;
    }

    public SmallClassRoomService() {
        super(__getWsdlLocation(), SMALLCLASSROOMSERVICE_QNAME);
    }

    public SmallClassRoomService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SMALLCLASSROOMSERVICE_QNAME, features);
    }

    public SmallClassRoomService(URL wsdlLocation) {
        super(wsdlLocation, SMALLCLASSROOMSERVICE_QNAME);
    }

    public SmallClassRoomService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SMALLCLASSROOMSERVICE_QNAME, features);
    }

    public SmallClassRoomService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SmallClassRoomService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ClassRoom
     */
    @WebEndpoint(name = "SmallClassRoomPort")
    public ClassRoom getSmallClassRoomPort() {
        return super.getPort(new QName("http://tomcatservice/", "SmallClassRoomPort"), ClassRoom.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ClassRoom
     */
    @WebEndpoint(name = "SmallClassRoomPort")
    public ClassRoom getSmallClassRoomPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://tomcatservice/", "SmallClassRoomPort"), ClassRoom.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SMALLCLASSROOMSERVICE_EXCEPTION!= null) {
            throw SMALLCLASSROOMSERVICE_EXCEPTION;
        }
        return SMALLCLASSROOMSERVICE_WSDL_LOCATION;
    }

}
