
package tomcatservice;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Student", targetNamespace = "http://tomcatservice/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Student {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Fail")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Fail", targetNamespace = "http://tomcatservice/", className = "tomcatservice.Fail")
    @ResponseWrapper(localName = "FailResponse", targetNamespace = "http://tomcatservice/", className = "tomcatservice.FailResponse")
    @Action(input = "http://tomcatservice/Student/FailRequest", output = "http://tomcatservice/Student/FailResponse")
    public String fail();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Pass")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Pass", targetNamespace = "http://tomcatservice/", className = "tomcatservice.Pass")
    @ResponseWrapper(localName = "PassResponse", targetNamespace = "http://tomcatservice/", className = "tomcatservice.PassResponse")
    @Action(input = "http://tomcatservice/Student/PassRequest", output = "http://tomcatservice/Student/PassResponse")
    public String pass();

}
