//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TomcatClientCSharp.tomcatServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tomcatservice/", ConfigurationName="tomcatServiceReference.CompositeServ")]
    public interface CompositeServ {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tomcatservice/CompositeServ/getClassNameRequest", ReplyAction="http://tomcatservice/CompositeServ/getClassNameResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TomcatClientCSharp.tomcatServiceReference.getClassNameResponse getClassName(TomcatClientCSharp.tomcatServiceReference.getClassNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tomcatservice/CompositeServ/getClassNameRequest", ReplyAction="http://tomcatservice/CompositeServ/getClassNameResponse")]
        System.Threading.Tasks.Task<TomcatClientCSharp.tomcatServiceReference.getClassNameResponse> getClassNameAsync(TomcatClientCSharp.tomcatServiceReference.getClassNameRequest request);
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tomcatservice/CompositeServ/setClassNameRequest", ReplyAction="http://tomcatservice/CompositeServ/setClassNameResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TomcatClientCSharp.tomcatServiceReference.setClassNameResponse setClassName(TomcatClientCSharp.tomcatServiceReference.setClassNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tomcatservice/CompositeServ/setClassNameRequest", ReplyAction="http://tomcatservice/CompositeServ/setClassNameResponse")]
        System.Threading.Tasks.Task<TomcatClientCSharp.tomcatServiceReference.setClassNameResponse> setClassNameAsync(TomcatClientCSharp.tomcatServiceReference.setClassNameRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tomcatservice/CompositeServ/getStudentRequest", ReplyAction="http://tomcatservice/CompositeServ/getStudentResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TomcatClientCSharp.tomcatServiceReference.getStudentResponse getStudent(TomcatClientCSharp.tomcatServiceReference.getStudentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tomcatservice/CompositeServ/getStudentRequest", ReplyAction="http://tomcatservice/CompositeServ/getStudentResponse")]
        System.Threading.Tasks.Task<TomcatClientCSharp.tomcatServiceReference.getStudentResponse> getStudentAsync(TomcatClientCSharp.tomcatServiceReference.getStudentRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tomcatservice/CompositeServ/RemoveStudentRequest", ReplyAction="http://tomcatservice/CompositeServ/RemoveStudentResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TomcatClientCSharp.tomcatServiceReference.RemoveStudentResponse RemoveStudent(TomcatClientCSharp.tomcatServiceReference.RemoveStudentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tomcatservice/CompositeServ/RemoveStudentRequest", ReplyAction="http://tomcatservice/CompositeServ/RemoveStudentResponse")]
        System.Threading.Tasks.Task<TomcatClientCSharp.tomcatServiceReference.RemoveStudentResponse> RemoveStudentAsync(TomcatClientCSharp.tomcatServiceReference.RemoveStudentRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tomcatservice/CompositeServ/getClassRoomRequest", ReplyAction="http://tomcatservice/CompositeServ/getClassRoomResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TomcatClientCSharp.tomcatServiceReference.getClassRoomResponse getClassRoom(TomcatClientCSharp.tomcatServiceReference.getClassRoomRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tomcatservice/CompositeServ/getClassRoomRequest", ReplyAction="http://tomcatservice/CompositeServ/getClassRoomResponse")]
        System.Threading.Tasks.Task<TomcatClientCSharp.tomcatServiceReference.getClassRoomResponse> getClassRoomAsync(TomcatClientCSharp.tomcatServiceReference.getClassRoomRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tomcatservice/CompositeServ/StartClassRequest", ReplyAction="http://tomcatservice/CompositeServ/StartClassResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TomcatClientCSharp.tomcatServiceReference.StartClassResponse StartClass(TomcatClientCSharp.tomcatServiceReference.StartClassRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tomcatservice/CompositeServ/StartClassRequest", ReplyAction="http://tomcatservice/CompositeServ/StartClassResponse")]
        System.Threading.Tasks.Task<TomcatClientCSharp.tomcatServiceReference.StartClassResponse> StartClassAsync(TomcatClientCSharp.tomcatServiceReference.StartClassRequest request);
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tomcatservice/CompositeServ/setClassRoomRequest", ReplyAction="http://tomcatservice/CompositeServ/setClassRoomResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TomcatClientCSharp.tomcatServiceReference.setClassRoomResponse setClassRoom(TomcatClientCSharp.tomcatServiceReference.setClassRoomRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tomcatservice/CompositeServ/setClassRoomRequest", ReplyAction="http://tomcatservice/CompositeServ/setClassRoomResponse")]
        System.Threading.Tasks.Task<TomcatClientCSharp.tomcatServiceReference.setClassRoomResponse> setClassRoomAsync(TomcatClientCSharp.tomcatServiceReference.setClassRoomRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tomcatservice/CompositeServ/AddStudentRequest", ReplyAction="http://tomcatservice/CompositeServ/AddStudentResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TomcatClientCSharp.tomcatServiceReference.AddStudentResponse AddStudent(TomcatClientCSharp.tomcatServiceReference.AddStudentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tomcatservice/CompositeServ/AddStudentRequest", ReplyAction="http://tomcatservice/CompositeServ/AddStudentResponse")]
        System.Threading.Tasks.Task<TomcatClientCSharp.tomcatServiceReference.AddStudentResponse> AddStudentAsync(TomcatClientCSharp.tomcatServiceReference.AddStudentRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tomcatservice/CompositeServ/getStudentsRequest", ReplyAction="http://tomcatservice/CompositeServ/getStudentsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TomcatClientCSharp.tomcatServiceReference.getStudentsResponse getStudents(TomcatClientCSharp.tomcatServiceReference.getStudentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tomcatservice/CompositeServ/getStudentsRequest", ReplyAction="http://tomcatservice/CompositeServ/getStudentsResponse")]
        System.Threading.Tasks.Task<TomcatClientCSharp.tomcatServiceReference.getStudentsResponse> getStudentsAsync(TomcatClientCSharp.tomcatServiceReference.getStudentsRequest request);
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tomcatservice/CompositeServ/setMaxStudentsRequest", ReplyAction="http://tomcatservice/CompositeServ/setMaxStudentsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TomcatClientCSharp.tomcatServiceReference.setMaxStudentsResponse setMaxStudents(TomcatClientCSharp.tomcatServiceReference.setMaxStudentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tomcatservice/CompositeServ/setMaxStudentsRequest", ReplyAction="http://tomcatservice/CompositeServ/setMaxStudentsResponse")]
        System.Threading.Tasks.Task<TomcatClientCSharp.tomcatServiceReference.setMaxStudentsResponse> setMaxStudentsAsync(TomcatClientCSharp.tomcatServiceReference.setMaxStudentsRequest request);
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tomcatservice/CompositeServ/setStudentRequest", ReplyAction="http://tomcatservice/CompositeServ/setStudentResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TomcatClientCSharp.tomcatServiceReference.setStudentResponse setStudent(TomcatClientCSharp.tomcatServiceReference.setStudentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tomcatservice/CompositeServ/setStudentRequest", ReplyAction="http://tomcatservice/CompositeServ/setStudentResponse")]
        System.Threading.Tasks.Task<TomcatClientCSharp.tomcatServiceReference.setStudentResponse> setStudentAsync(TomcatClientCSharp.tomcatServiceReference.setStudentRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tomcatservice/CompositeServ/getStundentNameRequest", ReplyAction="http://tomcatservice/CompositeServ/getStundentNameResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TomcatClientCSharp.tomcatServiceReference.getStundentNameResponse getStundentName(TomcatClientCSharp.tomcatServiceReference.getStundentNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tomcatservice/CompositeServ/getStundentNameRequest", ReplyAction="http://tomcatservice/CompositeServ/getStundentNameResponse")]
        System.Threading.Tasks.Task<TomcatClientCSharp.tomcatServiceReference.getStundentNameResponse> getStundentNameAsync(TomcatClientCSharp.tomcatServiceReference.getStundentNameRequest request);
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tomcatservice/CompositeServ/setStundentNameRequest", ReplyAction="http://tomcatservice/CompositeServ/setStundentNameResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TomcatClientCSharp.tomcatServiceReference.setStundentNameResponse setStundentName(TomcatClientCSharp.tomcatServiceReference.setStundentNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tomcatservice/CompositeServ/setStundentNameRequest", ReplyAction="http://tomcatservice/CompositeServ/setStundentNameResponse")]
        System.Threading.Tasks.Task<TomcatClientCSharp.tomcatServiceReference.setStundentNameResponse> setStundentNameAsync(TomcatClientCSharp.tomcatServiceReference.setStundentNameRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tomcatservice/CompositeServ/FailRequest", ReplyAction="http://tomcatservice/CompositeServ/FailResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TomcatClientCSharp.tomcatServiceReference.FailResponse Fail(TomcatClientCSharp.tomcatServiceReference.FailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tomcatservice/CompositeServ/FailRequest", ReplyAction="http://tomcatservice/CompositeServ/FailResponse")]
        System.Threading.Tasks.Task<TomcatClientCSharp.tomcatServiceReference.FailResponse> FailAsync(TomcatClientCSharp.tomcatServiceReference.FailRequest request);
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tomcatservice/CompositeServ/setStudentsRequest", ReplyAction="http://tomcatservice/CompositeServ/setStudentsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TomcatClientCSharp.tomcatServiceReference.setStudentsResponse setStudents(TomcatClientCSharp.tomcatServiceReference.setStudentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tomcatservice/CompositeServ/setStudentsRequest", ReplyAction="http://tomcatservice/CompositeServ/setStudentsResponse")]
        System.Threading.Tasks.Task<TomcatClientCSharp.tomcatServiceReference.setStudentsResponse> setStudentsAsync(TomcatClientCSharp.tomcatServiceReference.setStudentsRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tomcatservice/CompositeServ/getMaxStudentsRequest", ReplyAction="http://tomcatservice/CompositeServ/getMaxStudentsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TomcatClientCSharp.tomcatServiceReference.getMaxStudentsResponse getMaxStudents(TomcatClientCSharp.tomcatServiceReference.getMaxStudentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tomcatservice/CompositeServ/getMaxStudentsRequest", ReplyAction="http://tomcatservice/CompositeServ/getMaxStudentsResponse")]
        System.Threading.Tasks.Task<TomcatClientCSharp.tomcatServiceReference.getMaxStudentsResponse> getMaxStudentsAsync(TomcatClientCSharp.tomcatServiceReference.getMaxStudentsRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tomcatservice/CompositeServ/PassRequest", ReplyAction="http://tomcatservice/CompositeServ/PassResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TomcatClientCSharp.tomcatServiceReference.PassResponse Pass(TomcatClientCSharp.tomcatServiceReference.PassRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tomcatservice/CompositeServ/PassRequest", ReplyAction="http://tomcatservice/CompositeServ/PassResponse")]
        System.Threading.Tasks.Task<TomcatClientCSharp.tomcatServiceReference.PassResponse> PassAsync(TomcatClientCSharp.tomcatServiceReference.PassRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getClassName", WrapperNamespace="http://tomcatservice/", IsWrapped=true)]
    public partial class getClassNameRequest {
        
        public getClassNameRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getClassNameResponse", WrapperNamespace="http://tomcatservice/", IsWrapped=true)]
    public partial class getClassNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tomcatservice/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getClassNameResponse() {
        }
        
        public getClassNameResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setClassName", WrapperNamespace="http://tomcatservice/", IsWrapped=true)]
    public partial class setClassNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tomcatservice/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public setClassNameRequest() {
        }
        
        public setClassNameRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setClassNameResponse", WrapperNamespace="http://tomcatservice/", IsWrapped=true)]
    public partial class setClassNameResponse {
        
        public setClassNameResponse() {
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tomcatservice/")]
    public partial class student : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string stundentNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string stundentName {
            get {
                return this.stundentNameField;
            }
            set {
                this.stundentNameField = value;
                this.RaisePropertyChanged("stundentName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tomcatservice/")]
    public partial class smallClassRoom : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string classNameField;
        
        private int maxStudentsField;
        
        private student[] studentsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string className {
            get {
                return this.classNameField;
            }
            set {
                this.classNameField = value;
                this.RaisePropertyChanged("className");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int maxStudents {
            get {
                return this.maxStudentsField;
            }
            set {
                this.maxStudentsField = value;
                this.RaisePropertyChanged("maxStudents");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("students", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public student[] students {
            get {
                return this.studentsField;
            }
            set {
                this.studentsField = value;
                this.RaisePropertyChanged("students");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStudent", WrapperNamespace="http://tomcatservice/", IsWrapped=true)]
    public partial class getStudentRequest {
        
        public getStudentRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStudentResponse", WrapperNamespace="http://tomcatservice/", IsWrapped=true)]
    public partial class getStudentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tomcatservice/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TomcatClientCSharp.tomcatServiceReference.student @return;
        
        public getStudentResponse() {
        }
        
        public getStudentResponse(TomcatClientCSharp.tomcatServiceReference.student @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoveStudent", WrapperNamespace="http://tomcatservice/", IsWrapped=true)]
    public partial class RemoveStudentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tomcatservice/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TomcatClientCSharp.tomcatServiceReference.student arg0;
        
        public RemoveStudentRequest() {
        }
        
        public RemoveStudentRequest(TomcatClientCSharp.tomcatServiceReference.student arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoveStudentResponse", WrapperNamespace="http://tomcatservice/", IsWrapped=true)]
    public partial class RemoveStudentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tomcatservice/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public RemoveStudentResponse() {
        }
        
        public RemoveStudentResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getClassRoom", WrapperNamespace="http://tomcatservice/", IsWrapped=true)]
    public partial class getClassRoomRequest {
        
        public getClassRoomRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getClassRoomResponse", WrapperNamespace="http://tomcatservice/", IsWrapped=true)]
    public partial class getClassRoomResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tomcatservice/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TomcatClientCSharp.tomcatServiceReference.smallClassRoom @return;
        
        public getClassRoomResponse() {
        }
        
        public getClassRoomResponse(TomcatClientCSharp.tomcatServiceReference.smallClassRoom @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StartClass", WrapperNamespace="http://tomcatservice/", IsWrapped=true)]
    public partial class StartClassRequest {
        
        public StartClassRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StartClassResponse", WrapperNamespace="http://tomcatservice/", IsWrapped=true)]
    public partial class StartClassResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tomcatservice/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public StartClassResponse() {
        }
        
        public StartClassResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setClassRoom", WrapperNamespace="http://tomcatservice/", IsWrapped=true)]
    public partial class setClassRoomRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tomcatservice/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TomcatClientCSharp.tomcatServiceReference.smallClassRoom arg0;
        
        public setClassRoomRequest() {
        }
        
        public setClassRoomRequest(TomcatClientCSharp.tomcatServiceReference.smallClassRoom arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setClassRoomResponse", WrapperNamespace="http://tomcatservice/", IsWrapped=true)]
    public partial class setClassRoomResponse {
        
        public setClassRoomResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddStudent", WrapperNamespace="http://tomcatservice/", IsWrapped=true)]
    public partial class AddStudentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tomcatservice/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TomcatClientCSharp.tomcatServiceReference.student arg0;
        
        public AddStudentRequest() {
        }
        
        public AddStudentRequest(TomcatClientCSharp.tomcatServiceReference.student arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddStudentResponse", WrapperNamespace="http://tomcatservice/", IsWrapped=true)]
    public partial class AddStudentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tomcatservice/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public AddStudentResponse() {
        }
        
        public AddStudentResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStudents", WrapperNamespace="http://tomcatservice/", IsWrapped=true)]
    public partial class getStudentsRequest {
        
        public getStudentsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStudentsResponse", WrapperNamespace="http://tomcatservice/", IsWrapped=true)]
    public partial class getStudentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tomcatservice/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TomcatClientCSharp.tomcatServiceReference.student[] @return;
        
        public getStudentsResponse() {
        }
        
        public getStudentsResponse(TomcatClientCSharp.tomcatServiceReference.student[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setMaxStudents", WrapperNamespace="http://tomcatservice/", IsWrapped=true)]
    public partial class setMaxStudentsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tomcatservice/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public setMaxStudentsRequest() {
        }
        
        public setMaxStudentsRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setMaxStudentsResponse", WrapperNamespace="http://tomcatservice/", IsWrapped=true)]
    public partial class setMaxStudentsResponse {
        
        public setMaxStudentsResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setStudent", WrapperNamespace="http://tomcatservice/", IsWrapped=true)]
    public partial class setStudentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tomcatservice/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TomcatClientCSharp.tomcatServiceReference.student arg0;
        
        public setStudentRequest() {
        }
        
        public setStudentRequest(TomcatClientCSharp.tomcatServiceReference.student arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setStudentResponse", WrapperNamespace="http://tomcatservice/", IsWrapped=true)]
    public partial class setStudentResponse {
        
        public setStudentResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStundentName", WrapperNamespace="http://tomcatservice/", IsWrapped=true)]
    public partial class getStundentNameRequest {
        
        public getStundentNameRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStundentNameResponse", WrapperNamespace="http://tomcatservice/", IsWrapped=true)]
    public partial class getStundentNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tomcatservice/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getStundentNameResponse() {
        }
        
        public getStundentNameResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setStundentName", WrapperNamespace="http://tomcatservice/", IsWrapped=true)]
    public partial class setStundentNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tomcatservice/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public setStundentNameRequest() {
        }
        
        public setStundentNameRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setStundentNameResponse", WrapperNamespace="http://tomcatservice/", IsWrapped=true)]
    public partial class setStundentNameResponse {
        
        public setStundentNameResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Fail", WrapperNamespace="http://tomcatservice/", IsWrapped=true)]
    public partial class FailRequest {
        
        public FailRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FailResponse", WrapperNamespace="http://tomcatservice/", IsWrapped=true)]
    public partial class FailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tomcatservice/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public FailResponse() {
        }
        
        public FailResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setStudents", WrapperNamespace="http://tomcatservice/", IsWrapped=true)]
    public partial class setStudentsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tomcatservice/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("arg0", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TomcatClientCSharp.tomcatServiceReference.student[] arg0;
        
        public setStudentsRequest() {
        }
        
        public setStudentsRequest(TomcatClientCSharp.tomcatServiceReference.student[] arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setStudentsResponse", WrapperNamespace="http://tomcatservice/", IsWrapped=true)]
    public partial class setStudentsResponse {
        
        public setStudentsResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMaxStudents", WrapperNamespace="http://tomcatservice/", IsWrapped=true)]
    public partial class getMaxStudentsRequest {
        
        public getMaxStudentsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMaxStudentsResponse", WrapperNamespace="http://tomcatservice/", IsWrapped=true)]
    public partial class getMaxStudentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tomcatservice/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public getMaxStudentsResponse() {
        }
        
        public getMaxStudentsResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Pass", WrapperNamespace="http://tomcatservice/", IsWrapped=true)]
    public partial class PassRequest {
        
        public PassRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PassResponse", WrapperNamespace="http://tomcatservice/", IsWrapped=true)]
    public partial class PassResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tomcatservice/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public PassResponse() {
        }
        
        public PassResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CompositeServChannel : TomcatClientCSharp.tomcatServiceReference.CompositeServ, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CompositeServClient : System.ServiceModel.ClientBase<TomcatClientCSharp.tomcatServiceReference.CompositeServ>, TomcatClientCSharp.tomcatServiceReference.CompositeServ {
        
        public CompositeServClient() {
        }
        
        public CompositeServClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CompositeServClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CompositeServClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CompositeServClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TomcatClientCSharp.tomcatServiceReference.getClassNameResponse TomcatClientCSharp.tomcatServiceReference.CompositeServ.getClassName(TomcatClientCSharp.tomcatServiceReference.getClassNameRequest request) {
            return base.Channel.getClassName(request);
        }
        
        public string getClassName() {
            TomcatClientCSharp.tomcatServiceReference.getClassNameRequest inValue = new TomcatClientCSharp.tomcatServiceReference.getClassNameRequest();
            TomcatClientCSharp.tomcatServiceReference.getClassNameResponse retVal = ((TomcatClientCSharp.tomcatServiceReference.CompositeServ)(this)).getClassName(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TomcatClientCSharp.tomcatServiceReference.getClassNameResponse> TomcatClientCSharp.tomcatServiceReference.CompositeServ.getClassNameAsync(TomcatClientCSharp.tomcatServiceReference.getClassNameRequest request) {
            return base.Channel.getClassNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<TomcatClientCSharp.tomcatServiceReference.getClassNameResponse> getClassNameAsync() {
            TomcatClientCSharp.tomcatServiceReference.getClassNameRequest inValue = new TomcatClientCSharp.tomcatServiceReference.getClassNameRequest();
            return ((TomcatClientCSharp.tomcatServiceReference.CompositeServ)(this)).getClassNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TomcatClientCSharp.tomcatServiceReference.setClassNameResponse TomcatClientCSharp.tomcatServiceReference.CompositeServ.setClassName(TomcatClientCSharp.tomcatServiceReference.setClassNameRequest request) {
            return base.Channel.setClassName(request);
        }
        
        public void setClassName(string arg0) {
            TomcatClientCSharp.tomcatServiceReference.setClassNameRequest inValue = new TomcatClientCSharp.tomcatServiceReference.setClassNameRequest();
            inValue.arg0 = arg0;
            TomcatClientCSharp.tomcatServiceReference.setClassNameResponse retVal = ((TomcatClientCSharp.tomcatServiceReference.CompositeServ)(this)).setClassName(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TomcatClientCSharp.tomcatServiceReference.setClassNameResponse> TomcatClientCSharp.tomcatServiceReference.CompositeServ.setClassNameAsync(TomcatClientCSharp.tomcatServiceReference.setClassNameRequest request) {
            return base.Channel.setClassNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<TomcatClientCSharp.tomcatServiceReference.setClassNameResponse> setClassNameAsync(string arg0) {
            TomcatClientCSharp.tomcatServiceReference.setClassNameRequest inValue = new TomcatClientCSharp.tomcatServiceReference.setClassNameRequest();
            inValue.arg0 = arg0;
            return ((TomcatClientCSharp.tomcatServiceReference.CompositeServ)(this)).setClassNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TomcatClientCSharp.tomcatServiceReference.getStudentResponse TomcatClientCSharp.tomcatServiceReference.CompositeServ.getStudent(TomcatClientCSharp.tomcatServiceReference.getStudentRequest request) {
            return base.Channel.getStudent(request);
        }
        
        public TomcatClientCSharp.tomcatServiceReference.student getStudent() {
            TomcatClientCSharp.tomcatServiceReference.getStudentRequest inValue = new TomcatClientCSharp.tomcatServiceReference.getStudentRequest();
            TomcatClientCSharp.tomcatServiceReference.getStudentResponse retVal = ((TomcatClientCSharp.tomcatServiceReference.CompositeServ)(this)).getStudent(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TomcatClientCSharp.tomcatServiceReference.getStudentResponse> TomcatClientCSharp.tomcatServiceReference.CompositeServ.getStudentAsync(TomcatClientCSharp.tomcatServiceReference.getStudentRequest request) {
            return base.Channel.getStudentAsync(request);
        }
        
        public System.Threading.Tasks.Task<TomcatClientCSharp.tomcatServiceReference.getStudentResponse> getStudentAsync() {
            TomcatClientCSharp.tomcatServiceReference.getStudentRequest inValue = new TomcatClientCSharp.tomcatServiceReference.getStudentRequest();
            return ((TomcatClientCSharp.tomcatServiceReference.CompositeServ)(this)).getStudentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TomcatClientCSharp.tomcatServiceReference.RemoveStudentResponse TomcatClientCSharp.tomcatServiceReference.CompositeServ.RemoveStudent(TomcatClientCSharp.tomcatServiceReference.RemoveStudentRequest request) {
            return base.Channel.RemoveStudent(request);
        }
        
        public bool RemoveStudent(TomcatClientCSharp.tomcatServiceReference.student arg0) {
            TomcatClientCSharp.tomcatServiceReference.RemoveStudentRequest inValue = new TomcatClientCSharp.tomcatServiceReference.RemoveStudentRequest();
            inValue.arg0 = arg0;
            TomcatClientCSharp.tomcatServiceReference.RemoveStudentResponse retVal = ((TomcatClientCSharp.tomcatServiceReference.CompositeServ)(this)).RemoveStudent(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TomcatClientCSharp.tomcatServiceReference.RemoveStudentResponse> TomcatClientCSharp.tomcatServiceReference.CompositeServ.RemoveStudentAsync(TomcatClientCSharp.tomcatServiceReference.RemoveStudentRequest request) {
            return base.Channel.RemoveStudentAsync(request);
        }
        
        public System.Threading.Tasks.Task<TomcatClientCSharp.tomcatServiceReference.RemoveStudentResponse> RemoveStudentAsync(TomcatClientCSharp.tomcatServiceReference.student arg0) {
            TomcatClientCSharp.tomcatServiceReference.RemoveStudentRequest inValue = new TomcatClientCSharp.tomcatServiceReference.RemoveStudentRequest();
            inValue.arg0 = arg0;
            return ((TomcatClientCSharp.tomcatServiceReference.CompositeServ)(this)).RemoveStudentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TomcatClientCSharp.tomcatServiceReference.getClassRoomResponse TomcatClientCSharp.tomcatServiceReference.CompositeServ.getClassRoom(TomcatClientCSharp.tomcatServiceReference.getClassRoomRequest request) {
            return base.Channel.getClassRoom(request);
        }
        
        public TomcatClientCSharp.tomcatServiceReference.smallClassRoom getClassRoom() {
            TomcatClientCSharp.tomcatServiceReference.getClassRoomRequest inValue = new TomcatClientCSharp.tomcatServiceReference.getClassRoomRequest();
            TomcatClientCSharp.tomcatServiceReference.getClassRoomResponse retVal = ((TomcatClientCSharp.tomcatServiceReference.CompositeServ)(this)).getClassRoom(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TomcatClientCSharp.tomcatServiceReference.getClassRoomResponse> TomcatClientCSharp.tomcatServiceReference.CompositeServ.getClassRoomAsync(TomcatClientCSharp.tomcatServiceReference.getClassRoomRequest request) {
            return base.Channel.getClassRoomAsync(request);
        }
        
        public System.Threading.Tasks.Task<TomcatClientCSharp.tomcatServiceReference.getClassRoomResponse> getClassRoomAsync() {
            TomcatClientCSharp.tomcatServiceReference.getClassRoomRequest inValue = new TomcatClientCSharp.tomcatServiceReference.getClassRoomRequest();
            return ((TomcatClientCSharp.tomcatServiceReference.CompositeServ)(this)).getClassRoomAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TomcatClientCSharp.tomcatServiceReference.StartClassResponse TomcatClientCSharp.tomcatServiceReference.CompositeServ.StartClass(TomcatClientCSharp.tomcatServiceReference.StartClassRequest request) {
            return base.Channel.StartClass(request);
        }
        
        public string StartClass() {
            TomcatClientCSharp.tomcatServiceReference.StartClassRequest inValue = new TomcatClientCSharp.tomcatServiceReference.StartClassRequest();
            TomcatClientCSharp.tomcatServiceReference.StartClassResponse retVal = ((TomcatClientCSharp.tomcatServiceReference.CompositeServ)(this)).StartClass(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TomcatClientCSharp.tomcatServiceReference.StartClassResponse> TomcatClientCSharp.tomcatServiceReference.CompositeServ.StartClassAsync(TomcatClientCSharp.tomcatServiceReference.StartClassRequest request) {
            return base.Channel.StartClassAsync(request);
        }
        
        public System.Threading.Tasks.Task<TomcatClientCSharp.tomcatServiceReference.StartClassResponse> StartClassAsync() {
            TomcatClientCSharp.tomcatServiceReference.StartClassRequest inValue = new TomcatClientCSharp.tomcatServiceReference.StartClassRequest();
            return ((TomcatClientCSharp.tomcatServiceReference.CompositeServ)(this)).StartClassAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TomcatClientCSharp.tomcatServiceReference.setClassRoomResponse TomcatClientCSharp.tomcatServiceReference.CompositeServ.setClassRoom(TomcatClientCSharp.tomcatServiceReference.setClassRoomRequest request) {
            return base.Channel.setClassRoom(request);
        }
        
        public void setClassRoom(TomcatClientCSharp.tomcatServiceReference.smallClassRoom arg0) {
            TomcatClientCSharp.tomcatServiceReference.setClassRoomRequest inValue = new TomcatClientCSharp.tomcatServiceReference.setClassRoomRequest();
            inValue.arg0 = arg0;
            TomcatClientCSharp.tomcatServiceReference.setClassRoomResponse retVal = ((TomcatClientCSharp.tomcatServiceReference.CompositeServ)(this)).setClassRoom(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TomcatClientCSharp.tomcatServiceReference.setClassRoomResponse> TomcatClientCSharp.tomcatServiceReference.CompositeServ.setClassRoomAsync(TomcatClientCSharp.tomcatServiceReference.setClassRoomRequest request) {
            return base.Channel.setClassRoomAsync(request);
        }
        
        public System.Threading.Tasks.Task<TomcatClientCSharp.tomcatServiceReference.setClassRoomResponse> setClassRoomAsync(TomcatClientCSharp.tomcatServiceReference.smallClassRoom arg0) {
            TomcatClientCSharp.tomcatServiceReference.setClassRoomRequest inValue = new TomcatClientCSharp.tomcatServiceReference.setClassRoomRequest();
            inValue.arg0 = arg0;
            return ((TomcatClientCSharp.tomcatServiceReference.CompositeServ)(this)).setClassRoomAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TomcatClientCSharp.tomcatServiceReference.AddStudentResponse TomcatClientCSharp.tomcatServiceReference.CompositeServ.AddStudent(TomcatClientCSharp.tomcatServiceReference.AddStudentRequest request) {
            return base.Channel.AddStudent(request);
        }
        
        public bool AddStudent(TomcatClientCSharp.tomcatServiceReference.student arg0) {
            TomcatClientCSharp.tomcatServiceReference.AddStudentRequest inValue = new TomcatClientCSharp.tomcatServiceReference.AddStudentRequest();
            inValue.arg0 = arg0;
            TomcatClientCSharp.tomcatServiceReference.AddStudentResponse retVal = ((TomcatClientCSharp.tomcatServiceReference.CompositeServ)(this)).AddStudent(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TomcatClientCSharp.tomcatServiceReference.AddStudentResponse> TomcatClientCSharp.tomcatServiceReference.CompositeServ.AddStudentAsync(TomcatClientCSharp.tomcatServiceReference.AddStudentRequest request) {
            return base.Channel.AddStudentAsync(request);
        }
        
        public System.Threading.Tasks.Task<TomcatClientCSharp.tomcatServiceReference.AddStudentResponse> AddStudentAsync(TomcatClientCSharp.tomcatServiceReference.student arg0) {
            TomcatClientCSharp.tomcatServiceReference.AddStudentRequest inValue = new TomcatClientCSharp.tomcatServiceReference.AddStudentRequest();
            inValue.arg0 = arg0;
            return ((TomcatClientCSharp.tomcatServiceReference.CompositeServ)(this)).AddStudentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TomcatClientCSharp.tomcatServiceReference.getStudentsResponse TomcatClientCSharp.tomcatServiceReference.CompositeServ.getStudents(TomcatClientCSharp.tomcatServiceReference.getStudentsRequest request) {
            return base.Channel.getStudents(request);
        }
        
        public TomcatClientCSharp.tomcatServiceReference.student[] getStudents() {
            TomcatClientCSharp.tomcatServiceReference.getStudentsRequest inValue = new TomcatClientCSharp.tomcatServiceReference.getStudentsRequest();
            TomcatClientCSharp.tomcatServiceReference.getStudentsResponse retVal = ((TomcatClientCSharp.tomcatServiceReference.CompositeServ)(this)).getStudents(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TomcatClientCSharp.tomcatServiceReference.getStudentsResponse> TomcatClientCSharp.tomcatServiceReference.CompositeServ.getStudentsAsync(TomcatClientCSharp.tomcatServiceReference.getStudentsRequest request) {
            return base.Channel.getStudentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<TomcatClientCSharp.tomcatServiceReference.getStudentsResponse> getStudentsAsync() {
            TomcatClientCSharp.tomcatServiceReference.getStudentsRequest inValue = new TomcatClientCSharp.tomcatServiceReference.getStudentsRequest();
            return ((TomcatClientCSharp.tomcatServiceReference.CompositeServ)(this)).getStudentsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TomcatClientCSharp.tomcatServiceReference.setMaxStudentsResponse TomcatClientCSharp.tomcatServiceReference.CompositeServ.setMaxStudents(TomcatClientCSharp.tomcatServiceReference.setMaxStudentsRequest request) {
            return base.Channel.setMaxStudents(request);
        }
        
        public void setMaxStudents(int arg0) {
            TomcatClientCSharp.tomcatServiceReference.setMaxStudentsRequest inValue = new TomcatClientCSharp.tomcatServiceReference.setMaxStudentsRequest();
            inValue.arg0 = arg0;
            TomcatClientCSharp.tomcatServiceReference.setMaxStudentsResponse retVal = ((TomcatClientCSharp.tomcatServiceReference.CompositeServ)(this)).setMaxStudents(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TomcatClientCSharp.tomcatServiceReference.setMaxStudentsResponse> TomcatClientCSharp.tomcatServiceReference.CompositeServ.setMaxStudentsAsync(TomcatClientCSharp.tomcatServiceReference.setMaxStudentsRequest request) {
            return base.Channel.setMaxStudentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<TomcatClientCSharp.tomcatServiceReference.setMaxStudentsResponse> setMaxStudentsAsync(int arg0) {
            TomcatClientCSharp.tomcatServiceReference.setMaxStudentsRequest inValue = new TomcatClientCSharp.tomcatServiceReference.setMaxStudentsRequest();
            inValue.arg0 = arg0;
            return ((TomcatClientCSharp.tomcatServiceReference.CompositeServ)(this)).setMaxStudentsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TomcatClientCSharp.tomcatServiceReference.setStudentResponse TomcatClientCSharp.tomcatServiceReference.CompositeServ.setStudent(TomcatClientCSharp.tomcatServiceReference.setStudentRequest request) {
            return base.Channel.setStudent(request);
        }
        
        public void setStudent(TomcatClientCSharp.tomcatServiceReference.student arg0) {
            TomcatClientCSharp.tomcatServiceReference.setStudentRequest inValue = new TomcatClientCSharp.tomcatServiceReference.setStudentRequest();
            inValue.arg0 = arg0;
            TomcatClientCSharp.tomcatServiceReference.setStudentResponse retVal = ((TomcatClientCSharp.tomcatServiceReference.CompositeServ)(this)).setStudent(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TomcatClientCSharp.tomcatServiceReference.setStudentResponse> TomcatClientCSharp.tomcatServiceReference.CompositeServ.setStudentAsync(TomcatClientCSharp.tomcatServiceReference.setStudentRequest request) {
            return base.Channel.setStudentAsync(request);
        }
        
        public System.Threading.Tasks.Task<TomcatClientCSharp.tomcatServiceReference.setStudentResponse> setStudentAsync(TomcatClientCSharp.tomcatServiceReference.student arg0) {
            TomcatClientCSharp.tomcatServiceReference.setStudentRequest inValue = new TomcatClientCSharp.tomcatServiceReference.setStudentRequest();
            inValue.arg0 = arg0;
            return ((TomcatClientCSharp.tomcatServiceReference.CompositeServ)(this)).setStudentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TomcatClientCSharp.tomcatServiceReference.getStundentNameResponse TomcatClientCSharp.tomcatServiceReference.CompositeServ.getStundentName(TomcatClientCSharp.tomcatServiceReference.getStundentNameRequest request) {
            return base.Channel.getStundentName(request);
        }
        
        public string getStundentName() {
            TomcatClientCSharp.tomcatServiceReference.getStundentNameRequest inValue = new TomcatClientCSharp.tomcatServiceReference.getStundentNameRequest();
            TomcatClientCSharp.tomcatServiceReference.getStundentNameResponse retVal = ((TomcatClientCSharp.tomcatServiceReference.CompositeServ)(this)).getStundentName(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TomcatClientCSharp.tomcatServiceReference.getStundentNameResponse> TomcatClientCSharp.tomcatServiceReference.CompositeServ.getStundentNameAsync(TomcatClientCSharp.tomcatServiceReference.getStundentNameRequest request) {
            return base.Channel.getStundentNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<TomcatClientCSharp.tomcatServiceReference.getStundentNameResponse> getStundentNameAsync() {
            TomcatClientCSharp.tomcatServiceReference.getStundentNameRequest inValue = new TomcatClientCSharp.tomcatServiceReference.getStundentNameRequest();
            return ((TomcatClientCSharp.tomcatServiceReference.CompositeServ)(this)).getStundentNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TomcatClientCSharp.tomcatServiceReference.setStundentNameResponse TomcatClientCSharp.tomcatServiceReference.CompositeServ.setStundentName(TomcatClientCSharp.tomcatServiceReference.setStundentNameRequest request) {
            return base.Channel.setStundentName(request);
        }
        
        public void setStundentName(string arg0) {
            TomcatClientCSharp.tomcatServiceReference.setStundentNameRequest inValue = new TomcatClientCSharp.tomcatServiceReference.setStundentNameRequest();
            inValue.arg0 = arg0;
            TomcatClientCSharp.tomcatServiceReference.setStundentNameResponse retVal = ((TomcatClientCSharp.tomcatServiceReference.CompositeServ)(this)).setStundentName(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TomcatClientCSharp.tomcatServiceReference.setStundentNameResponse> TomcatClientCSharp.tomcatServiceReference.CompositeServ.setStundentNameAsync(TomcatClientCSharp.tomcatServiceReference.setStundentNameRequest request) {
            return base.Channel.setStundentNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<TomcatClientCSharp.tomcatServiceReference.setStundentNameResponse> setStundentNameAsync(string arg0) {
            TomcatClientCSharp.tomcatServiceReference.setStundentNameRequest inValue = new TomcatClientCSharp.tomcatServiceReference.setStundentNameRequest();
            inValue.arg0 = arg0;
            return ((TomcatClientCSharp.tomcatServiceReference.CompositeServ)(this)).setStundentNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TomcatClientCSharp.tomcatServiceReference.FailResponse TomcatClientCSharp.tomcatServiceReference.CompositeServ.Fail(TomcatClientCSharp.tomcatServiceReference.FailRequest request) {
            return base.Channel.Fail(request);
        }
        
        public string Fail() {
            TomcatClientCSharp.tomcatServiceReference.FailRequest inValue = new TomcatClientCSharp.tomcatServiceReference.FailRequest();
            TomcatClientCSharp.tomcatServiceReference.FailResponse retVal = ((TomcatClientCSharp.tomcatServiceReference.CompositeServ)(this)).Fail(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TomcatClientCSharp.tomcatServiceReference.FailResponse> TomcatClientCSharp.tomcatServiceReference.CompositeServ.FailAsync(TomcatClientCSharp.tomcatServiceReference.FailRequest request) {
            return base.Channel.FailAsync(request);
        }
        
        public System.Threading.Tasks.Task<TomcatClientCSharp.tomcatServiceReference.FailResponse> FailAsync() {
            TomcatClientCSharp.tomcatServiceReference.FailRequest inValue = new TomcatClientCSharp.tomcatServiceReference.FailRequest();
            return ((TomcatClientCSharp.tomcatServiceReference.CompositeServ)(this)).FailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TomcatClientCSharp.tomcatServiceReference.setStudentsResponse TomcatClientCSharp.tomcatServiceReference.CompositeServ.setStudents(TomcatClientCSharp.tomcatServiceReference.setStudentsRequest request) {
            return base.Channel.setStudents(request);
        }
        
        public void setStudents(TomcatClientCSharp.tomcatServiceReference.student[] arg0) {
            TomcatClientCSharp.tomcatServiceReference.setStudentsRequest inValue = new TomcatClientCSharp.tomcatServiceReference.setStudentsRequest();
            inValue.arg0 = arg0;
            TomcatClientCSharp.tomcatServiceReference.setStudentsResponse retVal = ((TomcatClientCSharp.tomcatServiceReference.CompositeServ)(this)).setStudents(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TomcatClientCSharp.tomcatServiceReference.setStudentsResponse> TomcatClientCSharp.tomcatServiceReference.CompositeServ.setStudentsAsync(TomcatClientCSharp.tomcatServiceReference.setStudentsRequest request) {
            return base.Channel.setStudentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<TomcatClientCSharp.tomcatServiceReference.setStudentsResponse> setStudentsAsync(TomcatClientCSharp.tomcatServiceReference.student[] arg0) {
            TomcatClientCSharp.tomcatServiceReference.setStudentsRequest inValue = new TomcatClientCSharp.tomcatServiceReference.setStudentsRequest();
            inValue.arg0 = arg0;
            return ((TomcatClientCSharp.tomcatServiceReference.CompositeServ)(this)).setStudentsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TomcatClientCSharp.tomcatServiceReference.getMaxStudentsResponse TomcatClientCSharp.tomcatServiceReference.CompositeServ.getMaxStudents(TomcatClientCSharp.tomcatServiceReference.getMaxStudentsRequest request) {
            return base.Channel.getMaxStudents(request);
        }
        
        public int getMaxStudents() {
            TomcatClientCSharp.tomcatServiceReference.getMaxStudentsRequest inValue = new TomcatClientCSharp.tomcatServiceReference.getMaxStudentsRequest();
            TomcatClientCSharp.tomcatServiceReference.getMaxStudentsResponse retVal = ((TomcatClientCSharp.tomcatServiceReference.CompositeServ)(this)).getMaxStudents(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TomcatClientCSharp.tomcatServiceReference.getMaxStudentsResponse> TomcatClientCSharp.tomcatServiceReference.CompositeServ.getMaxStudentsAsync(TomcatClientCSharp.tomcatServiceReference.getMaxStudentsRequest request) {
            return base.Channel.getMaxStudentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<TomcatClientCSharp.tomcatServiceReference.getMaxStudentsResponse> getMaxStudentsAsync() {
            TomcatClientCSharp.tomcatServiceReference.getMaxStudentsRequest inValue = new TomcatClientCSharp.tomcatServiceReference.getMaxStudentsRequest();
            return ((TomcatClientCSharp.tomcatServiceReference.CompositeServ)(this)).getMaxStudentsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TomcatClientCSharp.tomcatServiceReference.PassResponse TomcatClientCSharp.tomcatServiceReference.CompositeServ.Pass(TomcatClientCSharp.tomcatServiceReference.PassRequest request) {
            return base.Channel.Pass(request);
        }
        
        public string Pass() {
            TomcatClientCSharp.tomcatServiceReference.PassRequest inValue = new TomcatClientCSharp.tomcatServiceReference.PassRequest();
            TomcatClientCSharp.tomcatServiceReference.PassResponse retVal = ((TomcatClientCSharp.tomcatServiceReference.CompositeServ)(this)).Pass(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TomcatClientCSharp.tomcatServiceReference.PassResponse> TomcatClientCSharp.tomcatServiceReference.CompositeServ.PassAsync(TomcatClientCSharp.tomcatServiceReference.PassRequest request) {
            return base.Channel.PassAsync(request);
        }
        
        public System.Threading.Tasks.Task<TomcatClientCSharp.tomcatServiceReference.PassResponse> PassAsync() {
            TomcatClientCSharp.tomcatServiceReference.PassRequest inValue = new TomcatClientCSharp.tomcatServiceReference.PassRequest();
            return ((TomcatClientCSharp.tomcatServiceReference.CompositeServ)(this)).PassAsync(inValue);
        }
    }
}
