
package soapservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Calculator", targetNamespace = "http://soapservice/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Calculator {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod(operationName = "Add")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Add", targetNamespace = "http://soapservice/", className = "soapservice.Add")
    @ResponseWrapper(localName = "AddResponse", targetNamespace = "http://soapservice/", className = "soapservice.AddResponse")
    @Action(input = "http://soapservice/Calculator/AddRequest", output = "http://soapservice/Calculator/AddResponse")
    public int add(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod(operationName = "Substract")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Substract", targetNamespace = "http://soapservice/", className = "soapservice.Substract")
    @ResponseWrapper(localName = "SubstractResponse", targetNamespace = "http://soapservice/", className = "soapservice.SubstractResponse")
    @Action(input = "http://soapservice/Calculator/SubstractRequest", output = "http://soapservice/Calculator/SubstractResponse")
    public int substract(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
